/**
 * 🦉 Nigents - Backend Developer Agent
 * Writes backend code via OpenHands
 */

const BaseAgent = require('./base-agent');
const logger = require('../utils/logger');
const openhands = require('../tools/openhands');
const gitlab = require('../tools/gitlab');

class BackendDevAgent extends BaseAgent {
  constructor() {
    const config = require('../../config/agents.json')['backend-dev'];
    super(config);
  }

  /**
   * Implement the backend portion of a plan
   */
  async implement(plan) {
    this.setStatus('working', { task: 'implementing', plan: plan.title });
    this.currentTask = plan;

    try {
      this.emit('progress', { stage: 'setup', message: 'Setting up development environment...' });

      // Step 1: Setup - Clone repo and create branch
      const workDir = await this.setupWorkspace(plan);
      
      this.emit('progress', { stage: 'coding', message: 'Writing code...' });

      // Step 2: Implement each step in the plan
      const implementationResults = [];
      for (const step of plan.steps) {
        const result = await this.implementStep(step, workDir, plan);
        implementationResults.push(result);
        
        this.emit('progress', { 
          stage: 'coding', 
          message: `Completed step ${step.order}: ${step.description}`,
          step: step.order,
          total: plan.steps.length,
        });
      }

      this.emit('progress', { stage: 'committing', message: 'Committing changes...' });

      // Step 3: Commit and push
      const commitResult = await this.commitAndPush(workDir, plan);

      this.setStatus('done', { task: 'implementing', branch: plan.branch });
      
      return {
        success: true,
        branch: plan.branch,
        commit: commitResult,
        stepsCompleted: implementationResults.length,
        message: `Implementation complete. Branch: ${plan.branch}`,
      };
    } catch (error) {
      this.setStatus('error', { task: 'implementing', error: error.message });
      logger.error('[BackendDev] Error implementing:', error);
      return {
        success: false,
        message: `Implementation failed: ${error.message}`,
      };
    }
  }

  /**
   * Setup workspace - clone repo and create branch
   */
  async setupWorkspace(plan) {
    const project = plan.project;
    const branch = plan.branch;

    // Use OpenHands to setup the workspace
    const setupCommands = [
      `cd /workspace`,
      `git clone ${await gitlab.getRepoUrl(project)} ${project} || true`,
      `cd ${project}`,
      `git checkout -b ${branch}`,
    ];

    const result = await openhands.executeCommands(setupCommands);
    
    if (!result.success) {
      throw new Error(`Failed to setup workspace: ${result.error}`);
    }

    return `/workspace/${project}`;
  }

  /**
   * Implement a single step
   */
  async implementStep(step, workDir, plan) {
    const prompt = `
You are implementing this step of a plan:

STEP: ${step.description}
TYPE: ${step.type}
FILES: ${step.files.join(', ')}

OVERALL TASK: ${plan.title}
DESCRIPTION: ${plan.description}

WORKING DIRECTORY: ${workDir}

${step.type === 'create' 
  ? `Create the new file(s) with complete, working code. Include proper error handling, logging, and documentation.`
  : `Modify the existing file(s) to implement this step. Preserve existing functionality while adding the new feature.`
}

Use the write_file or edit_file tools to make changes.
Then verify the changes compile/build correctly.
`;

    // Use OpenHands to implement
    const result = await openhands.implementWithPrompt(prompt, workDir);
    
    return {
      step: step.order,
      success: result.success,
      files: step.files,
      output: result.output,
    };
  }

  /**
   * Commit and push changes
   */
  async commitAndPush(workDir, plan) {
    const commands = [
      `cd ${workDir}`,
      `git add -A`,
      `git commit -m "feat: ${plan.title}

${plan.description}

Changes:
${plan.steps.map(s => `- ${s.description}`).join('\n')}

Generated by Nigents 🤖"`,
      `git push origin ${plan.branch}`,
    ];

    const result = await openhands.executeCommands(commands);
    
    return {
      success: result.success,
      output: result.output,
    };
  }

  /**
   * Fix issues reported by QA or Reviewer
   */
  async fixIssues(branch, issues, workDir) {
    this.setStatus('working', { task: 'fixing_issues', issueCount: issues.length });

    const prompt = `
Fix the following issues in branch ${branch}:

${issues.map((issue, i) => `${i + 1}. ${issue.file}:${issue.line} - ${issue.message}`).join('\n')}

Make the necessary changes to resolve these issues.
`;

    const result = await openhands.implementWithPrompt(prompt, workDir);

    this.setStatus('done', { task: 'fixing_issues' });
    
    return {
      success: result.success,
      fixed: issues.length,
    };
  }

  /**
   * Handle specific backend technologies
   */
  async handleSpringBootTask(task) {
    // Specialized Spring Boot implementation logic
    const prompt = `
You are working on a Spring Boot application.

Task: ${task}

Requirements:
- Use Spring Boot best practices
- Include proper annotations (@RestController, @Service, @Repository, etc.)
- Add validation with @Valid
- Include proper exception handling
- Use Lombok if available
- Follow the existing package structure
- Add appropriate unit tests
`;
    return this.callClaude(prompt);
  }

  async handleNodeTask(task) {
    // Specialized Node.js implementation logic
    const prompt = `
You are working on a Node.js application.

Task: ${task}

Requirements:
- Use async/await, not callbacks
- Include proper error handling
- Use ES6+ features
- Follow the existing project structure
- Add JSDoc comments
- Include appropriate tests with Jest
`;
    return this.callClaude(prompt);
  }

  /**
   * Execute task - required by BaseAgent
   */
  async execute(task) {
    return this.implementBackend(task);
  }
}

module.exports = BackendDevAgent;
